"$schema" = 'https://starship.rs/config-schema.json'

[memory_usage]
disabled = false

[os]
disabled = false
[os.symbols]
Arch = " "

[package]
display_private = true

[shell]
disabled = false

[status]
disabled = false

[time]
disabled = false
