# fish completion for unity CLI
# To install:
#   unity completion fish | source
# Or save to the fish completions directory:
#   unity completion fish > ~/.config/fish/completions/unity.fish

# Disable default file completion
complete -c unity -f

# Global options
complete -c unity -l help -d "Show help"
complete -c unity -l version -d "Show version"
complete -c unity -s V -l version -d "output the version number"
complete -c unity -l format -a 'human json tsv ndjson github' -d "Output format: human, json, tsv, ndjson, github"
complete -c unity -l json -d "Shorthand for --format json"
complete -c unity -l no-banner -d "Suppress the startup banner"
complete -c unity -l no-pager -d "Disable the pager for long output"
complete -c unity -l non-interactive -d "Disable interactive prompts. Useful in CI/CD environments."
complete -c unity -l quiet -d "Suppress informational output"
complete -c unity -l verbose -d "Show full error details including stack traces on failure"
complete -c unity -l color -a 'auto always never' -d "Control colored output"
complete -c unity -l no-color -d "Disable colored output (shorthand for --color never)"
complete -c unity -l proxy -d "HTTP/HTTPS/SOCKS/PAC proxy URL. Examples: http://<user>:<pass>@host:8080, socks5://host:1080, pac+http://wpad/proxy.pac"
complete -c unity -l proxy-disable -d "Disable proxy for this invocation, ignoring all sources"
complete -c unity -l log-proxy -d "Log every outbound request to proxy-request.json for this run. Off by default; typically used once when reproducing a proxy issue for support. Also settable via UNITY_LOG_PROXY=1 or the proxyRequestLogging user setting."
complete -c unity -l no-log-proxy -d "Opt out of --log-proxy / UNITY_LOG_PROXY / the persisted user setting for this run. Use when logging is enabled globally but you want one clean invocation."

# Top-level commands
complete -c unity -f -n '__fish_use_subcommand' -a 'analytics' -d "Manage analytics and telemetry consent"
complete -c unity -f -n '__fish_use_subcommand' -a 'assets' -d "Inspect Unity asset packages"
complete -c unity -f -n '__fish_use_subcommand' -a 'auth' -d "Sign in, manage accounts, check login state, or sign out"
complete -c unity -f -n '__fish_use_subcommand' -a 'bug' -d "Report a bug directly to the Unity bug reporter (requires you to be signed in)"
complete -c unity -f -n '__fish_use_subcommand' -a 'build' -d "Build a Unity project from the command line. Spawns the editor in batch mode and forwards conventional CI flags."
complete -c unity -f -n '__fish_use_subcommand' -a 'cache' -d "Manage the download cache"
complete -c unity -f -n '__fish_use_subcommand' -a 'changelog' -d "Show release notes for the installed CLI"
complete -c unity -f -n '__fish_use_subcommand' -a 'ci' -d "Scaffold CI pipelines that drive the Unity CLI"
complete -c unity -f -n '__fish_use_subcommand' -a 'cloud' -d "Manage Unity Cloud organizations and projects"
complete -c unity -f -n '__fish_use_subcommand' -a 'collaboration' -d "Manage Unity Collaboration resources (annotations, attachments, Jira, reactions). Not version control; see unity vcs."
complete -c unity -f -n '__fish_use_subcommand' -a 'completion' -d "Print a shell completion script"
complete -c unity -f -n '__fish_use_subcommand' -a 'config' -d "View or change persistent CLI configuration"
complete -c unity -f -n '__fish_use_subcommand' -a 'context' -d "Save and switch between named sets of account, organization, project, editor and install path"
complete -c unity -f -n '__fish_use_subcommand' -a 'diagnose' -d "One-shot diagnostic commands for support — paste-safe, redacted output"
complete -c unity -f -n '__fish_use_subcommand' -a 'doctor' -d "Print diagnostic info about your Unity CLI environment"
complete -c unity -f -n '__fish_use_subcommand' -a 'editor' -d "Manage a Unity editor installation"
complete -c unity -f -n '__fish_use_subcommand' -a 'editors' -d "Manage Unity editors"
complete -c unity -f -n '__fish_use_subcommand' -a 'env' -d "Print Unity Hub environment paths and version"
complete -c unity -f -n '__fish_use_subcommand' -a 'hub' -d "Manage the Unity Hub application"
complete -c unity -f -n '__fish_use_subcommand' -a 'install' -d "Install a Unity editor"
complete -c unity -f -n '__fish_use_subcommand' -a 'job' -d "Manage detached Editor command jobs"
complete -c unity -f -n '__fish_use_subcommand' -a 'install-modules' -d "Install or list modules for an installed editor (fully interactive when no arguments provided)"
complete -c unity -f -n '__fish_use_subcommand' -a 'install-path' -d "Set or get the editor install path"
complete -c unity -f -n '__fish_use_subcommand' -a 'language' -d "Show or change the CLI display language"
complete -c unity -f -n '__fish_use_subcommand' -a 'license' -d "List the Unity licenses active on this machine"
complete -c unity -f -n '__fish_use_subcommand' -a 'list' -d "List tools available on the connected Unity Editor (commands registered by the Pipeline package)"
complete -c unity -f -n '__fish_use_subcommand' -a 'logs' -d "Read and tail the Hub log file"
complete -c unity -f -n '__fish_use_subcommand' -a 'mcp' -d "MCP server and client configuration for Unity Editor"
complete -c unity -f -n '__fish_use_subcommand' -a 'modules' -d "List and manage Unity editor modules"
complete -c unity -f -n '__fish_use_subcommand' -a 'pipeline' -d "Unity Editor Pipeline automation commands"
complete -c unity -f -n '__fish_use_subcommand' -a 'plugin' -d "View and manage the external components Unity installs for you"
complete -c unity -f -n '__fish_use_subcommand' -a 'projects' -d "Manage Unity projects in the Hub registry"
complete -c unity -f -n '__fish_use_subcommand' -a 'command' -d "Execute commands on connected Unity Editor instances, or list available commands"
complete -c unity -f -n '__fish_use_subcommand' -a 'commands' -d "List every command and subcommand as a machine-readable manifest"
complete -c unity -f -n '__fish_use_subcommand' -a 'templates' -d "Browse, inspect, create, edit, and delete Unity project templates"
complete -c unity -f -n '__fish_use_subcommand' -a 'test' -d "Run a project's EditMode/PlayMode tests in the editor and write a results report"
complete -c unity -f -n '__fish_use_subcommand' -a 'open' -d "Open a Unity project with the correct Editor version"
complete -c unity -f -n '__fish_use_subcommand' -a 'close' -d "Close the Unity editor that has a project open (exits without saving)"
complete -c unity -f -n '__fish_use_subcommand' -a 'run' -d "Run a Unity project in batch mode and forward args to the editor"
complete -c unity -f -n '__fish_use_subcommand' -a 'releases' -d "List available Unity releases"
complete -c unity -f -n '__fish_use_subcommand' -a 'self-uninstall' -d "Uninstall the unity CLI (removes the binary and environment files)"
complete -c unity -f -n '__fish_use_subcommand' -a 'shell' -d "Start an interactive shell (REPL) that runs many commands in one warm process"
complete -c unity -f -n '__fish_use_subcommand' -a 'skill' -d "Read the Unity CLI agent skill, or install it into an AI client"
complete -c unity -f -n '__fish_use_subcommand' -a 'status' -d "Show live state of every connected Unity Editor (port, project, version, PID, state)"
complete -c unity -f -n '__fish_use_subcommand' -a 'uninstall' -d "Uninstall an installed Unity editor"
complete -c unity -f -n '__fish_use_subcommand' -a 'self-update' -d "Update the unity CLI to the latest version"
complete -c unity -f -n '__fish_use_subcommand' -a 'vcs' -d "Version control for Unity projects: GitHub, GitLab, self-hosted git, UVCS. Not Unity Collaboration; see unity collab."
complete -c unity -f -n '__fish_use_subcommand' -a 'watch' -d "Watch a project and re-run a command each time its files change"
complete -c unity -f -n '__fish_use_subcommand' -a 'version' -d "Print the Unity CLI version and build information"

# Subcommand completions
complete -c unity -f -n '__fish_seen_subcommand_from analytics' -a 'opt-in' -d "Enable usage data collection"
complete -c unity -f -n '__fish_seen_subcommand_from analytics' -a 'opt-out' -d "Disable usage data collection"
complete -c unity -f -n '__fish_seen_subcommand_from analytics' -a 'status' -d "Show current analytics consent status"
complete -c unity -f -n '__fish_seen_subcommand_from assets' -a 'inspect' -d "List the contents of a .unitypackage without importing it"
complete -c unity -f -n '__fish_seen_subcommand_from auth' -a 'login' -d "Sign in to your Unity account (opens browser, or pass --client-id/--client-secret for a service account)"
complete -c unity -f -n '__fish_seen_subcommand_from auth' -a 'status' -d "Show whether you are signed in"
complete -c unity -f -n '__fish_seen_subcommand_from auth' -a 'list' -d "List stored accounts and show which one is active"
complete -c unity -f -n '__fish_seen_subcommand_from auth' -a 'switch' -d "Make a stored account the active account"
complete -c unity -f -n '__fish_seen_subcommand_from auth' -a 'default' -d "Show or set the default account for a Unity project"
complete -c unity -f -n '__fish_seen_subcommand_from auth' -a 'logout' -d "Sign out and clear stored credentials, or sign out one stored account"
complete -c unity -f -n '__fish_seen_subcommand_from auth' -a 'consumers' -d "List the applications that have used your sign-in"
complete -c unity -f -n '__fish_seen_subcommand_from auth' -a 'revoke' -d "Stop an application from using your sign-in"
complete -c unity -f -n '__fish_seen_subcommand_from build' -a 'run' -d "Launch the project's most recent successful build without rebuilding. Standalone players launch natively; WebGL builds are served from a local static server."
complete -c unity -f -n '__fish_seen_subcommand_from cache' -a 'info' -d "Show download cache location and size"
complete -c unity -f -n '__fish_seen_subcommand_from cache' -a 'clean' -d "Remove all files from the download cache"
complete -c unity -f -n '__fish_seen_subcommand_from cache' -a 'key' -d "Print a deterministic cache key for CI cache steps"
complete -c unity -f -n '__fish_seen_subcommand_from ci' -a 'init' -d "Write a CI workflow that installs the CLI, restores the caches, installs the editor, activates a license, tests, and builds"
complete -c unity -f -n '__fish_seen_subcommand_from cloud' -a 'status' -d "Show cloud sign-in state and active organization"
complete -c unity -f -n '__fish_seen_subcommand_from cloud' -a 'org' -d "Manage Unity Cloud organizations"
complete -c unity -f -n '__fish_seen_subcommand_from cloud' -a 'project' -d "Manage Unity Cloud projects"
complete -c unity -f -n '__fish_seen_subcommand_from collaboration' -a 'annotations' -d "Manage Unity Collaboration annotations"
complete -c unity -f -n '__fish_seen_subcommand_from collaboration' -a 'attachments' -d "Manage annotation attachments"
complete -c unity -f -n '__fish_seen_subcommand_from collaboration' -a 'jira' -d "Manage Unity Collaboration Jira integrations"
complete -c unity -f -n '__fish_seen_subcommand_from collaboration' -a 'reactions' -d "Manage emoji reactions on annotation threads"
complete -c unity -f -n '__fish_seen_subcommand_from collaboration' -a 'read' -d "Mark an annotation thread as read"
complete -c unity -f -n '__fish_seen_subcommand_from collaboration' -a 'subscribe' -d "Subscribe to notifications for an annotation thread"
complete -c unity -f -n '__fish_seen_subcommand_from collaboration' -a 'thumbnail' -d "Upload and download annotation thumbnails"
complete -c unity -f -n '__fish_seen_subcommand_from collaboration' -a 'unsubscribe' -d "Unsubscribe from notifications for an annotation thread"
complete -c unity -f -n '__fish_seen_subcommand_from completion' -a 'bash'
complete -c unity -f -n '__fish_seen_subcommand_from completion' -a 'zsh'
complete -c unity -f -n '__fish_seen_subcommand_from completion' -a 'fish'
complete -c unity -f -n '__fish_seen_subcommand_from completion' -a 'powershell'
complete -c unity -f -n '__fish_seen_subcommand_from config' -a 'proxy' -d "View or change the configured proxy server"
complete -c unity -f -n '__fish_seen_subcommand_from config' -a 'update-check' -d "Enable or disable the background check for CLI updates"
complete -c unity -f -n '__fish_seen_subcommand_from config' -a 'accelerator' -d "View or change the configured Unity Accelerator"
complete -c unity -f -n '__fish_seen_subcommand_from config' -a 'get' -d "Show the value of a configuration key"
complete -c unity -f -n '__fish_seen_subcommand_from config' -a 'set' -d "Set the value of a configuration key"
complete -c unity -f -n '__fish_seen_subcommand_from config' -a 'list' -d "List all configuration keys and their values"
complete -c unity -f -n '__fish_seen_subcommand_from config' -a 'unset' -d "Clear a configuration key"
complete -c unity -f -n '__fish_seen_subcommand_from config' -a 'resolve' -d "Show a build/test default's resolved value and which layer supplied it"
complete -c unity -f -n '__fish_seen_subcommand_from context' -a 'list' -d "List saved contexts"
complete -c unity -f -n '__fish_seen_subcommand_from context' -a 'current' -d "Show the active context and the settings it pins"
complete -c unity -f -n '__fish_seen_subcommand_from context' -a 'save' -d "Save your current settings as a named context"
complete -c unity -f -n '__fish_seen_subcommand_from context' -a 'use' -d "Apply a saved context"
complete -c unity -f -n '__fish_seen_subcommand_from context' -a 'delete' -d "Delete a saved context"
complete -c unity -f -n '__fish_seen_subcommand_from diagnose' -a 'proxy' -d "Print a redacted proxy diagnostic report and write a copy to the logs directory"
complete -c unity -f -n '__fish_seen_subcommand_from diagnose' -a 'update' -d "Show why this install is or is not updating"
complete -c unity -f -n '__fish_seen_subcommand_from diagnose' -a 'accelerator' -d "Show the resolved Unity Accelerator endpoint, the project cache server settings, and whether the endpoint answers"
complete -c unity -f -n '__fish_seen_subcommand_from editor' -a 'add' -d "Add an existing Unity editor to the Hub"
complete -c unity -f -n '__fish_seen_subcommand_from editor' -a 'module' -d "Manage modules for an installed editor"
complete -c unity -f -n '__fish_seen_subcommand_from editors' -a 'add' -d "Add an existing Unity editor to the Hub"
complete -c unity -f -n '__fish_seen_subcommand_from editors' -a 'default' -d "Show or set the default editor version used when no version is specified"
complete -c unity -f -n '__fish_seen_subcommand_from editors' -a 'list' -d "List installed Unity editors or available releases for download"
complete -c unity -f -n '__fish_seen_subcommand_from editors' -a 'running' -d "List running Unity editors and the project each has open"
complete -c unity -f -n '__fish_seen_subcommand_from editors' -a 'prune' -d "Find editors no registered project uses, and optionally uninstall them"
complete -c unity -f -n '__fish_seen_subcommand_from editors' -a 'verify' -d "Structurally verify an installed editor — check its files and modules are present on disk"
complete -c unity -f -n '__fish_seen_subcommand_from editors' -a 'info' -d "Show release details for a Unity editor version"
complete -c unity -f -n '__fish_seen_subcommand_from editors' -a 'module' -d "Manage modules for an installed editor"
complete -c unity -f -n '__fish_seen_subcommand_from editors' -a 'install-path' -d "Show or change the global editor install path"
complete -c unity -f -n '__fish_seen_subcommand_from editors' -a 'path' -d "Print the install directory of an installed Unity editor version"
complete -c unity -f -n '__fish_seen_subcommand_from editors' -a 'upgrade' -d "Upgrade an installed editor to the newest patch in its release line"
complete -c unity -f -n '__fish_seen_subcommand_from hub' -a 'install' -d "Install the Unity Hub"
complete -c unity -f -n '__fish_seen_subcommand_from job' -a 'status' -d "Show a detached job's state, progress, and result"
complete -c unity -f -n '__fish_seen_subcommand_from job' -a 'wait' -d "Wait for a detached job to finish and print its result"
complete -c unity -f -n '__fish_seen_subcommand_from job' -a 'cancel' -d "Request cancellation of a detached job"
complete -c unity -f -n '__fish_seen_subcommand_from license' -a 'list' -d "List the Unity licenses active on this machine"
complete -c unity -f -n '__fish_seen_subcommand_from license' -a 'status' -d "Show the current Unity license state"
complete -c unity -f -n '__fish_seen_subcommand_from license' -a 'activate' -d "Activate a Unity license"
complete -c unity -f -n '__fish_seen_subcommand_from license' -a 'return' -d "Return the active Unity licenses"
complete -c unity -f -n '__fish_seen_subcommand_from license' -a 'server' -d "Manage the floating license server"
complete -c unity -f -n '__fish_seen_subcommand_from mcp' -a 'configure' -d "Write MCP server config for an AI agent client"
complete -c unity -f -n '__fish_seen_subcommand_from modules' -a 'list' -d "List available modules for an editor version"
complete -c unity -f -n '__fish_seen_subcommand_from pipeline' -a 'install' -d "Install the Unity Pipeline package to a Unity project"
complete -c unity -f -n '__fish_seen_subcommand_from pipeline' -a 'upgrade' -d "Upgrade the Unity Pipeline package to the latest version if a newer one is available"
complete -c unity -f -n '__fish_seen_subcommand_from pipeline' -a 'list' -d "List all Unity Editor instances and their Pipeline package status"
complete -c unity -f -n '__fish_seen_subcommand_from pipeline' -a 'list-versions' -d "List all available versions of the Unity Pipeline package"
complete -c unity -f -n '__fish_seen_subcommand_from plugin' -a 'list' -d "List every external component with its kind, state, resolved path, and whether it came from the managed install or PATH"
complete -c unity -f -n '__fish_seen_subcommand_from plugin' -a 'changelog' -d "Show the release notes for a tool"
complete -c unity -f -n '__fish_seen_subcommand_from plugin' -a 'install' -d "Download and install a managed tool"
complete -c unity -f -n '__fish_seen_subcommand_from plugin' -a 'remove' -d "Remove the copy the Unity CLI installed"
complete -c unity -f -n '__fish_seen_subcommand_from plugin' -a 'upgrade' -d "Re-install a managed tool when its pinned build changed"
complete -c unity -f -n '__fish_seen_subcommand_from projects' -a 'list' -d "List Unity projects registered in the Hub"
complete -c unity -f -n '__fish_seen_subcommand_from projects' -a 'add' -d "Register existing Unity project folders in the Hub registry"
complete -c unity -f -n '__fish_seen_subcommand_from projects' -a 'clean' -d "Delete a project's regenerable cache folders (Library, Temp, Logs, …) to reclaim disk space"
complete -c unity -f -n '__fish_seen_subcommand_from projects' -a 'remove' -d "Remove projects from the Hub registry (does not delete files on disk)"
complete -c unity -f -n '__fish_seen_subcommand_from projects' -a 'info' -d "Show details for a local Unity project. Defaults to the current directory; pass a path or a name registered with the Hub."
complete -c unity -f -n '__fish_seen_subcommand_from projects' -a 'create' -d "Create a new Unity project and register it in the Hub"
complete -c unity -f -n '__fish_seen_subcommand_from projects' -a 'exec' -d "Run a command in every registered project that matches the filters"
complete -c unity -f -n '__fish_seen_subcommand_from projects' -a 'clone' -d "Clone a remote repository and register the Unity project it contains"
complete -c unity -f -n '__fish_seen_subcommand_from projects' -a 'link' -d "Enable Unity Cloud or version control for a local project"
complete -c unity -f -n '__fish_seen_subcommand_from projects' -a 'new' -d "Create a new Unity project (non-interactive, CI-friendly)"
complete -c unity -f -n '__fish_seen_subcommand_from projects' -a 'open' -d "Open a Unity project by name, fuzzy title match, or path"
complete -c unity -f -n '__fish_seen_subcommand_from projects' -a 'pin' -d "Pin (favorite) one or more projects by name or path pattern"
complete -c unity -f -n '__fish_seen_subcommand_from projects' -a 'unpin' -d "Unpin (unfavorite) one or more projects by name or path pattern"
complete -c unity -f -n '__fish_seen_subcommand_from projects' -a 'require' -d "Assert that the required editor version is installed, installing it if necessary"
complete -c unity -f -n '__fish_seen_subcommand_from projects' -a 'size' -d "Report a project's disk usage by folder, or summarize every registered project"
complete -c unity -f -n '__fish_seen_subcommand_from projects' -a 'verify' -d "Check a project for integrity problems that break a build, without launching the Editor"
complete -c unity -f -n '__fish_seen_subcommand_from projects' -a 'unlink' -d "Disable Unity Cloud or version control for a local project"
complete -c unity -f -n '__fish_seen_subcommand_from projects' -a 'upgrade' -d "Upgrade a Unity project to a different editor version"
complete -c unity -f -n '__fish_seen_subcommand_from projects' -a 'export' -d "Export the Hub project list to a JSON file"
complete -c unity -f -n '__fish_seen_subcommand_from projects' -a 'import' -d "Import a Hub project list from a previously exported JSON file"
complete -c unity -f -n '__fish_seen_subcommand_from projects' -a 'close' -d "Close the Unity editor that has a project open (exits without saving)"
complete -c unity -f -n '__fish_seen_subcommand_from templates' -a 'list' -d "List Unity project templates for an editor version"
complete -c unity -f -n '__fish_seen_subcommand_from templates' -a 'info' -d "Show detailed information about a Unity project template"
complete -c unity -f -n '__fish_seen_subcommand_from templates' -a 'create' -d "Create a custom template from an existing Unity project"
complete -c unity -f -n '__fish_seen_subcommand_from templates' -a 'pack' -d "Pack a Unity project into a portable template archive"
complete -c unity -f -n '__fish_seen_subcommand_from templates' -a 'delete' -d "Delete a user-generated custom template"
complete -c unity -f -n '__fish_seen_subcommand_from templates' -a 'location' -d "Get, set, or reset the default storage path for custom templates"
complete -c unity -f -n '__fish_seen_subcommand_from templates' -a 'edit' -d "Edit a custom (user-generated) template's metadata"
complete -c unity -f -n '__fish_seen_subcommand_from skill' -a 'show' -d "Print the embedded Unity CLI agent skill to stdout without installing it"
complete -c unity -f -n '__fish_seen_subcommand_from skill' -a 'install' -d "Install the Unity CLI skill into a specific AI client"
complete -c unity -f -n '__fish_seen_subcommand_from skill' -a 'refresh' -d "Re-render every previously installed Unity CLI skill against the currently-embedded tree"
complete -c unity -f -n '__fish_seen_subcommand_from vcs' -a 'setup' -d "Get this project into version control and push a first commit, asking only what cannot be detected"
complete -c unity -f -n '__fish_seen_subcommand_from vcs' -a 'status' -d "Show what changed, grouped by what it means to Unity, with meta-file pairing problems"
complete -c unity -f -n '__fish_seen_subcommand_from vcs' -a 'sync' -d "Pull safely: refuse while an Editor holds the project, pull the commits and the LFS objects, then report the reimport"
complete -c unity -f -n '__fish_seen_subcommand_from vcs' -a 'doctor' -d "Check the repository settings, ignore rules, LFS patterns, and package pinning a Unity project needs under version control"
complete -c unity -f -n '__fish_seen_subcommand_from vcs' -a 'providers' -d "Report which git provider this machine can reach, as whom, and what each host allows"
complete -c unity -f -n '__fish_seen_subcommand_from vcs' -a 'merge-setup' -d "Make Unity scene and prefab merges work in this repository, using the editor's UnityYAMLMerge tool"
complete -c unity -f -n '__fish_seen_subcommand_from vcs' -a 'switch' -d "Switch branches safely: refuse while an Editor holds the project, then report the reimport the switch causes"
complete -c unity -f -n '__fish_seen_subcommand_from vcs' -a 'conflicts' -d "List unresolved merge conflicts, classified by Unity type, with whether each one can merge automatically"
complete -c unity -f -n '__fish_seen_subcommand_from vcs' -a 'explain' -d "Explain in plain language what each branch changed in a conflicted Unity asset"
complete -c unity -f -n '__fish_seen_subcommand_from vcs' -a 'resolve' -d "Resolve a conflicted Unity asset with UnityYAMLMerge, or by taking one side"
complete -c unity -f -n '__fish_seen_subcommand_from vcs' -a 'diff' -d "Diff a scene or prefab by object and component name instead of by file id"
complete -c unity -f -n '__fish_seen_subcommand_from vcs' -a 'blame' -d "Show who last changed each GameObject and component in a scene or prefab"
complete -c unity -f -n '__fish_seen_subcommand_from vcs' -a 'summarize' -d "Summarize what a branch changed, ready to paste into a pull request"
complete -c unity -f -n '__fish_seen_subcommand_from vcs' -a 'affected' -d "Report which assets, assemblies, and tests a change affects"
complete -c unity -f -n '__fish_seen_subcommand_from vcs' -a 'hooks' -d "Manage the git hooks that run the Unity integrity checks at commit time"
complete -c unity -f -n '__fish_seen_subcommand_from vcs' -a 'git' -d "Git-only verbs, for the things UVCS has no equivalent of"
complete -c unity -f -n '__fish_seen_subcommand_from vcs' -a 'uvcs' -d "Unity Version Control reads that join cm's data to your project"
complete -c unity -f -n '__fish_seen_subcommand_from watch' -a 'test' -d "Re-run unity test --affected each time a project file changes"
