preload = /home/cookie/Pictures/Wallpapers/5g0faxqx3r181.png

wallpaper = HDMI-A-1,/home/cookie/Pictures/Wallpapers/5g0faxqx3r181.png
wallpaper = DVI-I-1,/home/cookie/Pictures/Wallpapers/5g0faxqx3r181.png

