monitor=HDMI-A-1,1920x1080@60,0x0,1
monitor=DVI-I-1,1920x1080@60,1920x0,1

workspace=HDMI-A-1,1
workspace=DVI-I-1,2

$HOME = /home/cookie
$APP_DIR = $HOME/Applications

$RUNNER = wofi

$TERM = alacritty
$FILES = index
$BROWSER = firefox
$TERM_CLS = Alacritty
$FILES_CLS = org.kde.index
$BROWSER_CLS = firefox

input {
    kb_layout=
    kb_variant=
    kb_model=
    kb_options=
    kb_rules=

    follow_mouse=1

    touchpad {
        natural_scroll=no
    }
}

general {
    sensitivity=1.0

    gaps_in=5
    gaps_out=10
    border_size=2
    col.active_border=0x665ce626
    col.inactive_border=0x66333333

    apply_sens_to_raw=1

    damage_tracking=full
}

decoration {
    rounding=10
    blur=1
    blur_size=3
    blur_passes=1
    blur_new_optimizations=1
}

animations {
    enabled=1
    animation=windows,1,4,default
    animation=border,1,8,default
    animation=fade,1,8,default
    animation=workspaces,1,4,default
}

dwindle {
    pseudotile=0
}

gestures {
    workspace_swipe=no
}

windowrule=monitor 1,$BROWSER_CLS
windowrule=monitor 1,$FILES_CLS
windowrule=monitor 2,$TERM_CLS

windowrule=workspace 1,$BROWSER_CLS
windowrule=workspace 2,$TERM_CLS
windowrule=workspace 3,$FILES_CLS

windowrule=float,^(org.gnome.*)$
windowrule=float,^(pinentry)
windowrule=float,^(virt-manager)$
windowrule=float,^(cmake-gui)$
windowrule=float,^(Bitwarden)$
windowrule=float,^(Popsicle)$
windowrule=float,^(apostrophe)$
windowrule=float,^(io.bassi.Amberol)$
windowrule=float,^(dev.geopjr.Collision)$

windowrule=tile,$FILES_CLS

windowrule=move 1500 40,^(waybar)$

windowrule=nofocus,^(Ibus-ui-gtk3)$

bind=SUPER,Q,killactive,
bind=CTRLSHIFT,escape,exit,
bind=SUPER,V,togglefloating,
bind=SUPER,P,pseudo,
bind=ALT,SPACE,exec,$RUNNER
bind=SUPER,T,exec,$TERM
bind=SUPER,E,exec,$FILES
bind=SUPER,B,exec,$BROWSER

bind=SUPER,SPACE,exec,bash -c ~/.config/hypr/scripts/ibus.sh
bind=SUPER,l,exec,bash -c ~/.config/hypr/scripts/waylock.sh
bind=ALTSHIFT,numbersign,exec,bash -c ~/.config/hypr/scripts/screenshot.sh
bind=CTRLALTSHIFT,numbersign,exec,bash -c ~/.config/hypr/scripts/screenclip.sh
bind=ALTSHIFT,dollar,exec,bash -c ~/.config/hypr/scripts/areashot.sh
bind=CTRLALTSHIFT,dollar,exec,bash -c ~/.config/hypr/scripts/areaclip.sh

bind=SUPER,left,movefocus,l
bind=SUPER,right,movefocus,r
bind=SUPER,up,movefocus,u
bind=SUPER,down,movefocus,d

bind=SUPERSHIFT,left,movewindow,l
bind=SUPERSHIFT,right,movewindow,r
bind=SUPERSHIFT,up,movewindow,u
bind=SUPERSHIFT,down,movewindow,d

bind=SUPERCTRL,left,resizeactive,-36 0
bind=SUPERCTRL,right,resizeactive,36 0
bind=SUPERCTRL,up,resizeactive,0 -36
bind=SUPERCTRL,down,resizeactive,0 36

bind=SUPER,Tab,workspace,e+1
bind=SUPER,1,workspace,1
bind=SUPER,2,workspace,2
bind=SUPER,3,workspace,3
bind=SUPER,4,workspace,4
bind=SUPER,5,workspace,5
bind=SUPER,6,workspace,6
bind=SUPER,7,workspace,7
bind=SUPER,8,workspace,8
bind=SUPER,9,workspace,9
bind=SUPER,0,workspace,10

bind=SUPERSHIFT,1,movetoworkspace,1
bind=SUPERSHIFT,2,movetoworkspace,2
bind=SUPERSHIFT,3,movetoworkspace,3
bind=SUPERSHIFT,4,movetoworkspace,4
bind=SUPERSHIFT,5,movetoworkspace,5
bind=SUPERSHIFT,6,movetoworkspace,6
bind=SUPERSHIFT,7,movetoworkspace,7
bind=SUPERSHIFT,8,movetoworkspace,8
bind=SUPERSHIFT,9,movetoworkspace,9
bind=SUPERSHIFT,0,movetoworkspace,10

exec-once=hyprpaper
exec-once=waybar
exec-once=dunst
exec-once=ibus-daemon -drxR
exec-once=com.spotify.Client
exec-once=$APP_DIR/pcloud
