general {
    ignore_empty_input = true
    immediate_render = true
}

background {
    monitor =
    path = ~/Pictures/Lock/background.png

    # all these options are taken from hyprland, see https://wiki.hyprland.org/Configuring/Variables/#blur for explanations
    blur_passes = 2
    blur_size = 4
}

image {
    monitor =
    path = ~/Pictures/Lock/profile.png
    size = 250
}

input-field {
    monitor =
    size = 400, 50
    dots_size = 0.5 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.25 # Scale of dots' absolute size, 0.0 - 1.0
    placeholder_text = <i>Input Password...</i> # Text rendered in the input box when it's empty.
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i> # can be set to empty

    position = 0, -15%
}

label {
    monitor =
    text = $TIME<br/>Hi there, $USER
    color = rgba(200, 200, 200, 1.0)
    font_size = 25
    font_family = JetBrains Mono

    position = 0, 10%
    halign = center
    valign = center
}
