# Hyprcursor variables
#env = HYPRCURSOR_THEME,MyCursor
env = HYPRCURSOR_SIZE,24
env = XCURSOR_SIZE,24

# XDG specifications.
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# GTK variables.
env = GDK_BACKEND,wayland,x11
env = GDK_SCALE,1
env = GDK_DPI_SCALE,1

# Qt variables.
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_ENABLE_HIGHDPI_SCALING,1
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_QPA_PLATFORMTHEME,qt6ct

# Electron variables.
env = ELECTRON_OZONE_PLATFORM_HINT,wayland

# Env for Nvidia.
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = LIBVA_DRIVER_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1
