# Execute your favorite apps at launch
exec-once = uwsm app -- dunst
exec-once = uwsm app -- fcitx5
exec-once = uwsm app -- wl-paste --type text --watch cliphist store
exec-once = uwsm app -- wl-paste --type image --watch cliphist store
exec-once = uwsm app -- udiskie &
exec-once = uwsm app -- pcmanfm-qt -d &

exec-once = uwsm app -- bash -c ~/.config/hypr/scripts/paper.sh
exec-once = systemctl --user start hypridle.service hyprpaper.service hyprpolkitagent.service waybar.service
