# Execute your favorite apps at launch
exec-once = hypridle
exec-once = wpaperd -d
exec-once = waybar
exec-once = dunst
exec-once = fcitx5
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = udiskie &
exec-once = pcmanfm-qt -d &

exec-once = /usr/lib/protonmail/bridge/proton-bridge --no-window --software-renderer
exec-once = flatpak run --command=telegram-desktop org.telegram.desktop -autostart
exec-once = flatpak run --command=com.discordapp.Discord com.discordapp.Discord
exec-once = /home/cookie/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox --minimize
