# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrule = suppressevent maximize, class:.* # You'll probably like this.

windowrule = float, class:^(.*)$
windowrule = tile, class:^(Alacritty)(.*)$
windowrule = tile, class:(pcmanfm-qt)$
windowrule = tile, class:(zathura)
windowrule = tile, class:(imv)
windowrule = tile, class:(mpv)
windowrule = tile, class:^(zen)(.*)$
windowrule = tile, class:^(codium)$
windowrule = tile, class:^(dev.zed.Zed)$
windowrule = tile, class:(VirtualBox Machine)$

windowrule = move cursor 10 10, class:^(waybar)$
# windowrule = move onscreen 100%-380 44, class:^(jetbrains-toolbox)$

windowrule = size 800 720, class:^(org.telegram.desktop)$
windowrule = move onscreen 10% 5%, class:^(org.telegram.desktop)$
windowrule = size 1200 720, class:^(com.discordapp.Discord)$
windowrule = move onscreen 5% 55%, class:^(com.discordapp.Discord)$
windowrule = size 1520 1600, class:^(org.mozilla.Thunderbird)$
windowrule = move onscreen 50% 5%, class:^(org.mozilla.Thunderbird)$
windowrule = size 1200 800, class:(Spotify)$
windowrule = center 1, class:(Spotify)$
windowrule = size 1200 800, class:(VirtualBox Manager)$
windowrule = center 1, class:(VirtualBox Manager)$
