# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.

windowrule = float, ^(.*)$
windowrule = tile, ^(Alacritty)(.*)$
windowrule = tile, ^(kitty)(.*)$
windowrulev2 = tile, class:(pcmanfm-qt)$
windowrulev2 = tile, class:(zathura)
windowrulev2 = tile, class:(imv)
windowrulev2 = tile, class:(mpv)
windowrulev2 = tile, class:^(zen)(.*)$
windowrulev2 = tile, class:^(brave-browser)$
windowrulev2 = tile, class:^(org.mozilla.Thunderbird)$
windowrulev2 = tile, class:^(codium)$
windowrulev2 = tile, class:^(dev.zed.Zed)$
windowrulev2 = tile, class:(VirtualBox Machine)$

windowrule = move cursor 10 10, ^(waybar)$
windowrule = move onscreen 100%-380 44, ^(jetbrains-toolbox)$

windowrulev2 = size 680 600, class:^(org.telegram.desktop)$
windowrulev2 = move onscreen 60% 20%, class:^(org.telegram.desktop)$
windowrulev2 = size 1180 700, class:^(com.discordapp.Discord)$
windowrulev2 = center 1, class:^(com.discordapp.Discord)$
windowrulev2 = size 1200 780, class:(Spotify)$
windowrulev2 = center 1, class:(Spotify)$
windowrulev2 = size 1200 780, class:(VirtualBox Manager)$
windowrulev2 = center 1, class:(VirtualBox Manager)$

windowrule = nofocus, ^(Ibus-ui-gtk3)$
