##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

windowrule = match:class .*, float on
windowrule = match:class Alacritty, tile on
windowrule = match:class pcmanfm-qt, tile on
windowrule = match:class .*zathura, tile on
windowrule = match:class imv, tile on
windowrule = match:class mpv, tile on
windowrule = match:class codium, tile on
windowrule = match:class .*zen.*, tile on
windowrule = match:class .*firefox.*, tile on
windowrule = match:class .*chromium.*, tile on
windowrule = match:class VirtualBox Machine, tile on

windowrule = match:class waybar, move cursor_x+10 cursor_y+10
# windowrule = match:class jetbrains-toolbox, move onscreen 100%-380 44

windowrule = match:class org.telegram.desktop, size 800 720
windowrule = match:class org.telegram.desktop, move monitor_w*0.1 monitor_h*0.05
windowrule = match:class com.discordapp.Discord, size 1280 720
windowrule = match:class com.discordapp.Discord, move 80 monitor_h*0.55
windowrule = match:class org.mozilla.Thunderbird, size 1760 1600
windowrule = match:class org.mozilla.Thunderbird, move monitor_w*0.45 monitor_h*0.05
windowrule = match:class Spotify, size 1200 800
windowrule = match:class Spotify, center on
windowrule = match:class VirtualBox Manager, size 1200 800
windowrule = match:class VirtualBox Manager, center on
