# Change mode keys
set -g mode-keys vi
bind Escape copy-mode
unbind '['

# More friendly split pane
bind-key h split-window -h
bind-key v split-window -v
unbind '"'
unbind %

# Extend history limit
set -g history-limit 10000

